### ISSUE TITLE
provide removed in react-redux core

### ISSUE THREAD

**Issue by amcdnl** [loggur/react-redux-provide#12]
I noticed that `provide` was removed from react-redux core per https://github.com/reactjs/react-redux/commit/09494885cad9cebd744b8bf05b3b22e45061c214

how does that decision to change the api affect the roadmap of this project? I personally favor the provide decorator but obvs the creator has other thoughts.

**Comment by FredyC** [comment]
I think you are in a wrong repo. It's quite old commit and they just removed decorator in favor of high order component because it made much more sense there.

**Comment by timbur** [comment]
@amcdnl The only thing this library uses from `react-redux` is the following:
```js
import shallowEqual from 'react-redux/lib/utils/shallowEqual';
import wrapActionCreators from 'react-redux/lib/utils/wrapActionCreators';
```

Other than that it is completely independent from `react-redux`.
