### ISSUE TITLE
Possible 'providedState' conflict with multiple stores?

### ISSUE THREAD

**Issue by dy2288** [loggur/react-redux-provide#13]
Not sure if this is a bug or me misunderstanding the usage of _providedState_ ;-)

When using multiple stores for multiple providers -- it looks like the  _providedState_ is checked against all reducers. If they happen to share the same name, this could result in unexpected side-affects.

```
const context = {
  providers, // providePage + provideCustom
  providedState: {
    transformUI: {menuVisible: false}
  }
};

render(<AppWrapper { ...context } />, document.getElementById('app-wrapper'))
```

If both 'providePage' and 'provideCustom' have the 'transformUI' recuder, the initial state will be applied to both (Line 27 in createProviderStore.js).

Would it not make more sense to do something like this for example:
```
  providedState: [
    providePage: { transformUI: {menuVisible: false} }
    provideCustom: { transformUI: {menuVisible: true} }
  ]
```

Really enjoying this library btw. Seems very intuitive to me!

**Comment by timbur** [comment]
Thanks!  I do actually have a solution for this particular problem in the works, which involves using store keys to automatically initialize multiple stores of the same type as necessary based on component props and context.  So after that's completed, the problem you've outlined should be solved as well.  I'll add that it's recommend that it looks more like this:
```js
  providedState: {
    page: { transformUI: {menuVisible: false} }
    custom: { transformUI: {menuVisible: true} }
  }
```

The store keys in that particular case would be `page` and `custom`.  And another one of the changes I'll make will allow you to specify a function which can map store keys to provided states.  So suppose you have some comments from different users and you have a comment provider.  I'm not 100% sure about this API yet but it might look something like:
```js
  providedState: (props, context) {
    const userId = props.userId || context.userId;
    const commentId = props.commentId;
    const postId = props.postId;

    return {
      [`userId=${userId}`&commentId=${commentId}&postId=${postId}`]: {
        autoFocus: typeof commentId === 'undefined'
      }
  }
```

The idea is for there to be enough information for replicators to have enough information based on the store key to retrieve what it needs from some database and then automatically initialize the state of the store.

I had to take an unexpected break from working on this last week and haven't been able to get back to it just yet.  But Monday I should resume work on all of this.  :)

**Comment by dy2288** [comment]
Cool, I think both these suggestions would help solve the problem.

On a side note, I wonder if I'm better off specifying the default values in the reducers themselves whenever possible. I think trying to maintain and organize default values by using providedState could get complex if you're changing the hierarchy of your store state often or even to trace where a value came from. I guess this is also a good argument for keeping your state as simple and flat as possible..

**Comment by timbur** [comment]
Yeah, the default values should typically come from the reducers themselves, while the `providedState` is exactly what it's named after - i.e., it's the state you'll be providing to the components, usually derived from some database and/or specific to the page, user, etc., which is the portion that replicators are meant to help out with.
