### ISSUE TITLE
Stateless component functions produce warning

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#14]
So I am slowly diving into this and apparently there is a general issue when trying to combine `provide` for stateless component function. I tried to use as a decorator, but Babel doesn't like that in general, so I simply wrapped exported function into `provide` and got this warning.

`Warning: Stateless function components cannot be given refs (See ref "wrappedInstance" in SignIn created by ProvideSignIn()). Attempts to access this ref will fail.`

Essentially it seems to be working, but having such warning for every wrapped component isn't that nice :)

**Comment by FredyC** [comment]
Also it seems that warning is not only issue, but when this happens, no props are passed down to wrapped component.

**Comment by timbur** [comment]
Ah okay I'll push a patch real quick.  This library is designed for `class` components but yeah it would be nice to work with plain functions.  :)

Also, see #13 for some updates coming next week!  The updates will also solve #11.

**Comment by FredyC** [comment]
Thank you for a quick response!

Yea, I don't like either to specify propTypes separately on prototype. I am planning to try the approach of [react-stampit](https://github.com/stampit-org/react-stamp) which looks really interesting when examined more closely. Hopefully it will work out of box with `provide`.

I have seen updates, but I've not actually run into those issues yet, so had no need to examine it that deeply, but surely might be handy, specially #13.

**Comment by timbur** [comment]
Can you try `v5.2.3` and let me know if there are anymore problems?

**Comment by FredyC** [comment]
Well warning is no longer shown, but props are not passed either way...
![](https://dl.dropboxusercontent.com/u/1791518/github/react-redux-provide/stateless-function-props.PNG)

**Comment by timbur** [comment]
Weird.  I'll try to fix it.

**Comment by timbur** [comment]
What props are not passed down and do you have `propTypes` on your stateless function component(s)?  What are the `propTypes`?

**Comment by FredyC** [comment]
I have this SignIn component...

**Comment by FredyC** [comment]
It's about props that I pass manually from the top component, like that `className` I highlighted. It's not passed into the wrapped SignIn component.

	function SignIn({ className, signInWithProvider }) {
		return (<div className={className}>...</div>);
	}

	SignIn.prototype.propTypes = {
		className: PT.string.isRequired,
	};

	import provide from 'react-redux-provide';
	export default provide(SignIn);

And then I create that component like...

    <SignIn className={styles.signIn} />

**Comment by timbur** [comment]
Oh I think the problem is this:
```js
SignIn.prototype.propTypes = {
    className: PT.string.isRequired,
};
```

It should be:
```js
SignIn.propTypes = {
    className: PT.string.isRequired,
};
```

Also if you want `signInWithProvider` you'll need to specify that `propType` as well.

**Comment by FredyC** [comment]
I see, that works. So the `provide` doesn't pass down anything that's not defined in propTypes? Is that necessary? I am not saying that propTypes shouldn't be consistent, but I would thought that `provide` would just grab everything it received and pass it down. Seems like unnecessary runtime check.

**Comment by timbur** [comment]
I designed it that way to make `shouldComponentUpdate` more efficient, so that it doesn't compare props that the component isn't actually using.  You're right that there's probably a better way to do that though.  Maybe the best thing to do is to pass down everything but during `shouldComponentUpdate`, only compare the props specified as `propTypes`.  I'll think about it some more when implementing #13.

**Comment by timbur** [comment]
> so that it doesn't compare props that the component isn't actually using.

Oh, to clarify: so that it doesn't compare props *from the stores' states* that the component isn't actually using.

**Comment by FredyC** [comment]
I guess that make sense. I kinda like it that I have to keep consistent propTypes, but what bothers me that it's failing silently. Perhaps there could be some development warnings if there is some prop passed from parent but it's not expected by a child?

Either way I think we can close this as the main issue was solved. Thank you again.
