### ISSUE TITLE
State not persisting across stores in React Native

### ISSUE THREAD

**Issue by jonlong** [loggur/react-redux-provide#15]
Hey, thanks for a great library! I think this approach feels really solid, and I'm excited to see how far it goes. I get the feeling I may be missing something elementary here, but I'm having trouble tracking it down.

I'm using this library with React Native and finding that my state is not persisting across `@provide`d components when my scenes change. Each of my scenes calls a component that is decorated with the `@provide` method, and as soon as it mounts, the `@@INIT` action is fired. 

If I trigger any actions within that scene, they'll fire properly and populate my store correctly. However, as soon as the scene changes, `@@INIT` is triggered again and the stored state is reset.

I'd love to get some help figuring out if I've got a configuration issue, or if I'm missing something fundamental.

I've got a test case set up at https://github.com/jonlong/react-redux-provide-troubleshooting and am happy to provide any more info!

**Comment by timbur** [comment]
It sounds like the `context` (which contains the current providers/states) is somehow getting lost or overridden.  I haven't used `react-native` yet, but my first guess is that it's causing the app is to reinitialize (which generates new `context`) upon each scene change.  In the short term, the only thing I can think of that would fix this for you is to pass the `providedState` prop to your top level component and ensure it is always up to date.  For the long term, I am working on a better data replication design, which will help with persisting/initializing stores (i.e., problems like this one, among many others).  Apologies for any delay on the long term solution.  The past few weeks have been rough and I'm still trying to get back into the swing of things.

Do you know what `react-native`'s rendering/scene change process looks like?  It does seem strange to be that the app might be remounting itself each time.

I'd be glad to help you with a solution that keeps the `providedState` up-to-date.  There are a few different ways to do this, though I'm not sure which is best for `react-native`.

**Comment by jonlong** [comment]
Thanks for the tip! Just so I'm clear, is the `context` that you're referencing the initial set of props passed to the app component ([like in this example](https://github.com/loggur/react-redux-provide/blob/master/examples%2Fgood-times%2Findex.js#L7-L14)), or the value of `this.context` within a component ([as described in these docs](https://facebook.github.io/react/docs/context.html))?

I'm thinking I may be running into an issue where [Navigator](https://facebook.github.io/react-native/docs/navigator.html) is preventing values expected by `react-redux-provide` from passing between routes on scene change — I'm just not sure what those values are yet.

**Comment by timbur** [comment]
Cool.  Please let me know if there's anything I can do to help.

**Comment by jonlong** [comment]
Solved it! Thanks for the tip on `context`. Super simple, and nothing to do with RN. Turns out that I didn't have my wrapper component (the one that contains my router) decorated with `@provide`.

I think it wasn't obvious because I was associating `@provide` with the props I'd need in the components themselves, and not thinking about the parent/child relationship needed to pass the stores around.

So, my router was swapping out child components that had no `context` to reference — hence the stores getting re-initialized.

Thanks for helping me find the issue!

**Comment by timbur** [comment]
Nice!  Glad to see you figured it out.

**Comment by timbur** [comment]
Hey, just so you know, v6.0 now includes an `install` function so that you don't have to remember to wrap your components with `provide`.  This also allows `react-redux-provide` to work much better with `react-router` than v5 did.  There is now an official router provider at [`provide-router`](https://github.com/loggur/provide-router).  I like how it turned out so much that I'll be updating all of my examples/boilerplates to use it.  👍

**Comment by jonlong** [comment]
Awesome, thanks so much for updating me! Love to see this project progress so well — you're doing an impressive job!
