### ISSUE TITLE
Consider ignoring .babelrc on publish

### ISSUE THREAD

**Issue by jonlong** [loggur/react-redux-provide#17]
React Native's made the migration to Babel 6, which has the unfortunate side effect of finding `.babelrc` files in `node_modules` and attempting to use those configurations (see [this issue](https://github.com/facebook/react-native/issues/4062) for more details). 

As a result, Babel 5 configs break RN builds, and the team's [official fix](https://github.com/facebook/react-native/issues/4062#issuecomment-179944792) is to ask module authors if they would consider adding `.babelrc` to `.npmignore`.

Wanted to ask if you'd be up for it — no problems otherwise using this lib with RN :)

**Comment by timbur** [comment]
Thanks!  This will be in v6.0.0 which should be released within the next few days, hopefully.
