### ISSUE TITLE
Provider for rAF based animation

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#19]
This is something I am still bit confused about React in general. How to do GPU driven animation using `requestAnimationFrame`. I wasn't able to find satisfying answer yet, so it got me thinking that it might be a good candidate for a provider perhaps. 

I am thinking about something like specifying `onAnimationTick: PT.func.isRequired` which would be essentially an action and reducer would add callback to the state that is supposed to be called on every tick. It could also return cancel function that would hold internal ID of that callback to be removed when requested.

Provider could be even initialized with custom tick provider or even routine how to calculate the delta that can be shared by every component that requests it.

@timbur Do you think it's a good fit for provider or would you use completely different approach? Can you spot any hurdles that might prevent this to work correctly?

**Comment by timbur** [comment]
Yes a provider sounds like it would be perfect for this use case!

**Comment by timbur** [comment]
How's this going?  Can we close this?

**Comment by FredyC** [comment]
Well I haven't really tried to implemented it yet as there were more important things to do. I'll close it now and reopen if some issue with it arise later.
