### ISSUE TITLE
Vagueness in documentation?

### ISSUE THREAD

**Issue by adamdonahue** [loggur/react-redux-provide#20]
First off, this looks promising.  Nice work.

I did a quick read through of the tutorial, and one thing is unclear to me: in the example you are calling the action creators directly as part of the `onClick` action on the buttons, but it's not immediately clear how these are hooked up to the redux `dispatch` function, particularly in the case where you want to pass parameters to the action creators.  

For example, if I have

```
render() {
  return <button onClick={this.props.increment}>Increment</button>;
}
```

how is this in turn dispatched to redux, and how would you handle the dynamic passing of arguments to the action creator?  My guess without looking at the source code is that you wrap each action creator in a parent function that first calls the real action creator and then issues a dispatch, but again it's a bit confusing in that, for a basic `onClick` handler, at least, the first parameter is going to be the event object, not a `by` parameter, unless you're somehow dealing with that as well.

Anyhow, I was hoping you could clarity this confusion on my part.

Thanks.

Adam

**Comment by timbur** [comment]
Hey, thanks!  I am always trying to make this as clear and understandable as possible.  Please lmk if the above commit (readme clarification 9607f99163d031af3562c9fd7e4f8991be7ddb71) answers your question.

**Comment by timbur** [comment]
I'll also add that the tutorial is currently incomplete.  Trying to finish it asap, as soon as some other things are finished.  :)

**Comment by adamdonahue** [comment]
This definitely clarifies things.  Thanks.

I still have a question about the example.  I think you want:

```
<button onClick={() => this.props.increment()}>Increment</button>
```

Otherwise `this.props.increment` will be called with an event object (`e`, traditionally) as its first parameter.
