### ISSUE TITLE
Registering a provider with no reducers and provided state throws error

### ISSUE THREAD

**Issue by psachs21** [loggur/react-redux-provide#23]
I have two providers, one maintains some reducers and state and actions, and another that only has some actions: 

```
const provider1 = { actions: { ... } };
const provider2 = { reducers: ..., etc... };

pushEnhancer(
  providers: { provider1, provider2 }
);

const context = {
  providers,
  providedState: {
    list: []
  }
};

render(<App { ...context }/>, document.getElementById('app'));
```

This is a simplified version so hopefully it errors out. I get the following error: ```createProviderStore.js?b2d0:40 Uncaught TypeError: Cannot read property 'list' of undefined``` 

I can work around it by specifying a useless reducer but I don't think that should be necessary.

I think a simple guard in createProvideStore: ln 40 to prevent the check if no reducer exists would probably work.

**Comment by psachs21** [comment]
Apparently I hadn't updated to the newest version. Different error now. I tried fixing it myself but there seems to be a few places where a provider is assumed to have some kind of reducer.

**Comment by psachs21** [comment]
This is probably just an issue with how I was using the provider. Doesn't really make sense to create a different provider that is only made up of actions.

**Comment by timbur** [comment]
Glad to see you worked it out.  :+1: 

Regarding your example code, `providedState` has been replaced with an optional `state` object on the provider itself.  For example:
```js
// src/defaultProps.js

import awesomeTheme from './themes/awesome';

providers.theme.state = {
  themeName: 'awesome',
  theme: awesomeTheme
};
```

And this also allows us to initialize different states for the same types of providers with different keys:
```js
// src/defaultProps.js
// or maybe src/providers/user.js
// etc., etc.

providers.user.key = ({ props }) => `userId=${props.userId}`;
```

```js
// and then when generating the document HTML
// etc., etc.
<script>
// from some database or whatever + JSON.stringify
window.clientState = {
  'userId=123': {
    userName: 'psachs21',
    etc: 'etc'
  },

  'userId=456': {
    name: 'STH',
    etc: 'etc'
  }
};
</script>
```

```js
// and then suppose we have some UserInfo component, or anything really

export default class UserInfo extends Component {
  static propTypes = {
    classes: PropTypes.object.isRequired,
    userId: PropTypes.number.isRequired,
    userName: PropTypes.string.isRequired
  };

  render() {
    return (
      <div className={this.props.classes.UserInfo}>
        {this.props.userName
          ? `User ${this.props.userId} is ${this.props.userName}.`
          : `Loading user ${this.props.userId}...`
        }
      </div>
    );
  }
}
```

Might as well discuss the other two pieces while we're at it.  :smile: 

Manage user state just like you would anything else:
```js
// src/providers/user.js

const actions = { login, logout, updateUserName, ...etc };

const reducers = {
  userId(state, action) {
    return etc;
  },

  userName(state, action) {
    return etc;
  }
};

export default { actions, reducers };
```

And hook it up to some database on the server via replication:
```js
import rethinkDB from 'redux-replicate-rethinkdb';

providers.user.replication = {
  // key defaults to same provider key: `userId=${userId}` but you can override the key for replication if you need
  reducerKeys: ['userId', 'userName'],
  replicator: rethinkDB
};
```
