### ISSUE TITLE
Inter provider communication?

### ISSUE THREAD

**Issue by psachs21** [loggur/react-redux-provide#25]
I'm playing around with the provider concept and I wanted to get an idea of how I might have one provider send an action to another provider without having a component in between. 

The particular example I'm thinking about is with regards to using redux-sagas to fire off other actions to other providers.

**Comment by timbur** [comment]
Good question.  You would need `context` at the very least, since that's where the provider instances are cached (since they're instantiated within the React components via the `providers` prop).  You can access provider instances by their key within `context.providerInstances`, and then you can use the provider instance's store to dispatch the action - e.g., `context.providerInstances[someProviderKey].store.dispatch({ type: SOME_ACTION, etc })`.  Can you think of a real world scenario where this might be required?  Might help with imagining the best API for something like this.

**Comment by SeeThruHead** [comment]
So after watching this talk (https://www.youtube.com/watch?v=09ddrCaLo10&index=15&list=PLb0IAmt7-GS0M8Q95RIc2lOM6nc77q1IY) the other day it got me thinking about tree's of providers.

Providers could be laid out in a tree the same way that react components are, and providers on a current level return the original state (meaning the don't handle the action) we could pass the action up to the parent. Not sure which state the parent receives (perhaps it's state + the keys for it's children's state in the same tree.)

We have an issue where we'd like to use different providers to store different data required for our application. One section might be a map of items to show the user while another might be transient ui state. We use sagas to handle all user interactions and as such we would like to be able to fire off actions from these sagas ie: set a loading spinner bool in the ui state provider, and set a new item in the item-data provider in response to a resolving promise. Currently we can't do that while using two stores. An interesting thing to note is that the saga's that handle user interaction actually doesn't need it own store. It is merely a central hub to send user interactions actions to. It would be interesting to think about store-less providers for this use case.

**Comment by timbur** [comment]
A provider tree sounds interesting!

Is your loading spinner something shown at the top level of the app or is it contained within components as they're loading?  And may I see some example code?

**Comment by psachs21** [comment]
The idea would be that there is a top level component that contains the loading state as well as some other state information. We don't actually have the code quite yet, we're in the process of writing it. This is more of a theoretical hurdle that we foresee coming shortly.

In general, I think some method of providers being able to bubble their actions would make sense for applications of scale.

**Comment by SeeThruHead** [comment]
Yeah like Paul said we haven't written this as we're currently in very early stages of the app.

a normal action flow for a user interaction would look something like this
```javascript
function *hello() {
  yield take('BEGIN_REQUEST')
  yield put({ type: 'SHOW_WAITING_MODAL' })
  const response = yield call(myApiFunctionThatWrapsFetch)
  yield put({ type: 'PRELOAD_IMAGES', response.images })
  yield put({ type: 'SET_SOME_DATA', data: response.data })
  yield put({ type: 'USAGE_TRACK', activity: 'API_CALL'})
  yield put({ type: 'HIDE_WAITING_MODAL' })
}
```

Show and hide waiting modal both fire actions to the ui provider,
preload images could be caught by a saga and not need a store, or the promises could be cached in the ui store

set some data would go to a provider (likely a map) that handles just storing and mutating data
usages track could go to another provider which might have a websocket replicator to push events to a streaming analytics pipeline

This saga is our best way of interacting with the multiple separate domains of our application (more specialized providers) and it does not need a store of it's own. So I imagine this being at the top level of a provider tree, handling all actions that it's children do not, and being able to dispatch actions that will be passed to each of it's children and eventually itself if not caught.

**Comment by timbur** [comment]
I see.  Hmmm... I really like this idea!  Let's continue brainstorming.  How would you want the React components to use all of this?

**Comment by SeeThruHead** [comment]
Typically for actions we're only firing off saga actions from the UI, actions that do not correspond to a store, they would normally get caught but the top level providers' set of sagas.

It would be nice to keep retrieving action creators and state from providers in components flat as it currently is. We would just do namespacing.

Another thought that occurred to me that we get with this is that canned providers delivered as pluggable modules can do a lot more than manage their own state now, they can fire off actions for logging, analytics and other side effects without caring about whether or not they are handled. IF you wan to handle them you can just respond to them in your root provider. I think this get's us a little bit closer to powerful pluggable redux architecture.

**Comment by SeeThruHead** [comment]
So perhaps this could be a middleware that we push into all children providers that passes all child actions to their parent provider. We also need a way to pass all bound action-creators of all children providers to it's parents sagas.

**Comment by timbur** [comment]
Alright sorry for the 1.5 month delay lol.  I'll be honest, I had a really tough time to make everything work the way I wanted while remaining fully compatible with the Redux ecosystem, but replication + declarative queries + automatically server (re)rendering is finally 99% complete.

In the process of implementing these things, I think I found a really good solution to inter-provider communication.  There are actually a couple of different ways but the best one that I found was to include a custom thunk middleware with all providers which allows you to do this:

```js
// src/providers/fooProvider.js

const key = ({ props }) => typeof props.fooProviderId === 'undefined'
  ? `fooProvider`
  : `fooProviderId=${props.fooProviderId}`;

const actions = {
  // accessing providers of same type
  accessAnotherInstanceOfFooProvider({ anotherProviderId }) {
    return (dispatch, getState, getInstance) => { // note extra `getInstance`
      const { fooProviderId } = getState();

      dispatch({
        type: ACCESSING_FOO,
        fooProviderId: anotherProviderId
      });

      getInstance({ fooProviderId: anotherProviderId }, fooProviderInstance => {
        // by this point the fooProviderInstance will be fully initialized,
        // regardless of whether or not it had already been instantiated
        dispatch({
          type: ACCESSED_FOO,
          fooProviderId: anotherProviderId
        });

        fooProviderInstance.store.dispatch({
          type: ACCESSED_BY_FOO,
          fooProviderId
        });
      });
    };
  },

  // accessing providers of other type(s)
  accessBarProvider({ barProviderId }) {
    return (dispatch, getState, getInstance) => { // note extra `getInstance`
      const { fooProviderId } = getState();

      dispatch({
        type: ACCESSING_BAR,
        barProviderId
      });

      // you'll need to either import `barProvider`
      // or turn this into a provider factory and pass `barProvider` to it
      // or find some other way to ensure `barProvider` is defined
      getInstance(barProvider, { barProviderId }, barProviderInstance => {
        dispatch({
          type: ACCESSED_BAR,
          barProviderId
        });

        barProviderInstance.store.dispatch({
          type: ACCESSED_BY_FOO,
          fooProviderId
        });
      });
    };
  }
};

const reducers = {
  fooProviderId(state = 0, action) {
    // omitting these details for the sake of brevity,
    // but pretend we have a CREATE action that sets this ID (ultimately replicated to a DB);
    // almost finished creating a provider factory (or factories) to be used for common things like this
  },

  lastAccessedBy(state = null, action) {
    // etc.
  },

  lastFooAccessed(state = null, action) {
    // etc.
  },

  lastBarAccessed(state = null, action) {
    // etc.
  }
};
```

**Comment by ms88privat** [comment]
@timbur thanks for your hard work on this. Maybe you could write an example to this specification here:
https://github.com/slorber/scalable-frontend-with-elm-or-redux

Would be interesting

**Comment by timbur** [comment]
@ms88privat Thanks, I will definitely check that out and see what I can come up with.  Sounds like it should be pretty easy using providers.  😁

**Comment by timbur** [comment]
Some updates since my last comment: 

- Eliminated the need for importing other providers when getting them within action creators.  This eliminates any unnecessary dependencies and allows the provider instances to be retrieved from context just like every other provider.

- Added the ability to find (query) provider instances by their state(s) within action creators.  It's designed to keep the replicator's responses to queries in the same order, so that any sorting/grouping will be left entirely up to the replicator (i.e., replicator => the glue between Redux state(s) and database(s)).

Here's an example of a `user` provider with creation and authentication:
```js
// src/providers/user.js

import { canUseDOM } from 'exenv';

export const CREATING_USER = 'CREATING_USER';
export const CREATE_USER = 'CREATE_USER';
export const CREATED_USER = 'CREATED_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGGED_IN = 'LOGGED_IN';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';

const key = ({ props }) => typeof props.userId === 'undefined'
  ? `user`
  : `userId=${props.userId}`;

const actions = {
  createUser(state, genUserId, onSuccess) {
    if (canUseDOM) {
      return { type: CREATING_USER };
    }

    return (dispatch, getState, getInstance, find) => {
      const {
        userName,
        userPassword,
        encryptor = getState().encryptor,
        saltRounds = getState().saltRounds
      } = state;

      if (!userName) {
        dispatch(actions.setUserError('Enter a name!'));
        return;
      }

      if (!userPassword) {
        dispatch(actions.setUserError('Enter a password!'));
        return;
      }

      find({ query: { userName }, options: { select: 'userId' } }, results => {
        if (results && results.length) {
          dispatch(actions.setUserError('User exists!'));
          return;
        }

        encryptor.hash(userPassword, saltRounds, (error, userPasswordHash) => {
          if (!userPasswordHash) {
            dispatch(actions.setUserError('Error hashing password!'));
            return;
          }

          state.userId = genUserId();

          getInstance(state, userInstance => {
            userInstance.store.dispatch({
              ...state,
              userPasswordHash,
              type: CREATE_USER
            });

            dispatch({
              ...state,
              type: CREATED_USER
            });

            if (onSuccess) {
              onSuccess(state.userId);
            }
          });
        });
      });
    };
  },

  setUserError(userError) {
    return actions.updateUser({ userError });
  },

  updateUser(state) {
    return { ...state, type: UPDATE_USER };
  },

  authenticateUser(userName, userPassword, onSuccess) {
    if (canUseDOM) {
      return { type: AUTHENTICATING_USER, userName };
    }

    if (!userName) {
      return actions.setUserError('Enter a name!');
    }

    if (!userPassword) {
      return actions.setUserError('Enter a password!');
    }

    return (dispatch, getState, getInstance, find) => {
      find({ query: { userName } }, true, results => {
        const userInstance = results && results[0];

        if (!userInstance) {
          dispatch(actions.setUserError('User not found!'));
          return;
        }

        const userStore = userInstance.store;
        const userState = userStore.getState();
        const {
          userPasswordHash,
          encryptor = getState().encryptor
        } = userState;

        encryptor.compare(userPassword, userPasswordHash, (error, matches) => {
          if (!matches) {
            dispatch(actions.setUserError('Wrong password!'));
            return;
          }

          dispatch({ type: AUTHENTICATED_USER });
          userStore.dispatch({ type: LOGGED_IN });

          if (onSuccess) {
            onSuccess(userState.userId);
          }
        });
      });
    };
  }
};

const reducers = {
  userId(state = -1, action) {
    switch (action.type) {
      case CREATE_USER:
      case UPDATE_USER:
        return typeof action.userId === 'undefined'
          ? state
          : action.userId;

      default:
        return state;
    }
  },

  userName(state = '', action) {
    switch (action.type) {
      case CREATE_USER:
      case UPDATE_USER:
        return typeof action.userName === 'undefined'
          ? state
          : action.userName;

      default:
        return state;
    }
  },

  userPasswordHash(state = '', action) {
    switch (action.type) {
      case CREATE_USER:
      case UPDATE_USER:
        return typeof action.userPasswordHash === 'undefined'
          ? state
          : action.userPasswordHash;

      default:
        return state;
    }
  },

  userError(state = '', action) {
    switch (action.type) {
      case CREATE_USER:
      case UPDATE_USER:
        return typeof action.userError === 'undefined'
          ? state
          : action.userError;

      case CREATED_USER:
      case AUTHENTICATED_USER:
        return '';

      default:
        return state;
    }
  },

  encryptor(state = null, action) {
    switch (action.type) {
      case CREATE_USER:
      case UPDATE_USER:
        return typeof action.encryptor === 'undefined'
          ? state
          : action.encryptor;

      default:
        return state;
    }
  },

  saltRounds(state = 12, action) {
    switch (action.type) {
      case CREATE_USER:
      case UPDATE_USER:
        return typeof action.saltRounds === 'undefined'
          ? state
          : action.saltRounds;

      default:
        return state;
    }
  }
};

const replication = {
  reducerKeys: ['userId', 'userName', 'userPasswordHash'],
  queryable: ['userName']
};

const clientStateKeys = [
  'userId',
  'userName'
];

export default {
  key, actions, reducers, replication, clientStateKeys
};
```

And then the `UserLogIn` component is pretty simple:
```js
// src/components/UserLogIn.js

import React, { Component, PropTypes } from 'react';
import { Form } from 'provide-page';

export default class UserLogIn extends Component {
  static propTypes = {
    classes: PropTypes.object.isRequired,
    formId: PropTypes.string,
    formData: PropTypes.object,
    genUserId: PropTypes.func.isRequired,
    createUser: PropTypes.func.isRequired,
    authenticateUser: PropTypes.func.isRequired,
    userError: PropTypes.string.isRequired,
    updateSession: PropTypes.func.isRequired
  };

  static defaultProps = {
    formId: 'UserLogIn'
  };

  logIn = (event, formData) => {
    if (this.isSigningUp(formData)) {
      this.props.createUser(
        formData,
        this.genUserId,
        this.updateSessionUserId
      );
    } else {
      this.props.authenticateUser(
        formData.userName,
        formData.userPassword,
        this.updateSessionUserId
      );
    }
  };

  genUserId = () => {
    return this.props.genUserId();
  };

  updateSessionUserId = (userId) => {
    this.props.updateSession({ userId });
  };

  isSigningUp(formData) {
    return formData.which === 'signUp'  // client
      || !formData.which && typeof formData.signUp !== 'undefined'; // server
  }

  setWhich = (event) => {
    this.refs.which.value = event.target.name;
  };

  render() {
    const { classes, formId, formData, userError } = this.props;
    const { userName, userPassword } = formData || {};

    return (
      <Form
        className={classes.UserLogIn}
        formId={formId}
        onSubmit={this.logIn}
      >
        <div className={classes.UserNameInputWrapper}>
          <input
            className={classes.UserNameInput}
            type="text"
            name="userName"
            ref="userNameInput"
            placeholder="Name"
            defaultValue={userName}
            onKeyDown={event => {
              if (event.key === 'Enter') {
                event.stopPropagation();
                event.preventDefault();
                this.refs.userPasswordInput.focus();
              }
            }}
          />
        </div>

        <div className={classes.UserPasswordInputWrapper}>
          <input
            className={classes.UserPasswordInput}
            type="password"
            name="userPassword"
            ref="userPasswordInput"
            placeholder="Password"
            defaultValue={userPassword}
          />
        </div>

        <div className={classes.LogInOrSignUp}>
          <button
            className={classes.LogInButton}
            type="submit"
            name="logIn"
            ref="logInButton"
            onClick={this.setWhich}
          >
            Log in
          </button>

          <button
            className={classes.SignUpButton}
            type="submit"
            name="signUp"
            ref="signUpButton"
            onClick={this.setWhich}
          >
            Sign up
          </button>

          <input type="hidden" name="which" ref="which" />
        </div>

        <div className={classes.UserError}>
          {userError}
        </div>
      </Form>
    );
  }
}
```

**Comment by timbur** [comment]
Just added the ability for providers to automatically subscribe to other providers (and vice versa), using `someProvider.subscribers = { ... }` and/or `someProvider.subscribeTo = { ... }`.  I'll update the docs when I get a chance but for now the following example should suffice for anyone wondering.

So for instance, suppose you want to have a static `theme` provider, but you want the instance's state to depend on the currently logged in user.  When a user logs in/out, the `user` provider might set the `userId` on the `page` provider's `requestSession` object.  And in which case, you could design the `theme` provider to subscribe to the `page` provider and update the theme store's key like so...

From https://github.com/loggur/lumbur/blob/c17677aff014725f062c8eb8ac4f6f05800f8b8a/src/providers/theme.js:
```js
import theme from 'provide-theme';

function getThemeKey(pageState) {
  const { userId = -1 } = pageState.requestSession;

  return userId < 0 ? null : `theme&userId=${userId}`;
}

theme.replication.key = null;

theme.subscribeTo = {
  page({ store: pageStore }, { store: themeStore }) {
    if (themeStore.setKey) {
      const themeKey = getThemeKey(pageStore.getState());

      if (themeKey !== themeStore.key) {
        themeStore.setKey(themeKey);
      }
    }
  }
};

export default theme;
```

The above is also equivalent to this (but don't do both because that would be silly):
```js
import page from 'provide-page';

function getThemeKey(pageState) {
  const { userId = -1 } = pageState.requestSession;

  return userId < 0 ? null : `theme&userId=${userId}`;
}

page.subscribers = {
  theme({ store: pageStore }, { store: themeStore }) {
    if (themeStore.setKey) {
      const themeKey = getThemeKey(pageStore.getState());

      if (themeKey !== themeStore.key) {
        themeStore.setKey(themeKey);
      }
    }
  }
};

export default page;
```

**Comment by ms88privat** [comment]
someday I will have some spare time and I will try your stuff out, keep working on it 👍

**Comment by timbur** [comment]
Okie dokie.  This repo's README is updated.  😅 

Double checking all the others now...
