### ISSUE TITLE
Adding ref to component returns the provided node instead of wrapped node

### ISSUE THREAD

**Issue by psachs21** [loggur/react-redux-provide#26]
So this is an interesting problem. When trying to use DraftJS editor in my app, I am unable to use the ref for the editor to access the APIs usually available. I think this is because the Component has instance methods that are obscured by provide.

Setup:

1. Using in ```import 'react-redux-provide/lib/install'```
2. Include DraftJS editor component.

```js
import React, { PropTypes, Component } from 'react';
import { Editor, EditorState } from 'draft-js';

export default class MessageBox extends Component {
  render() {
    return <Editor editorState={editorState} onChange={this.onChange}
          ref={node => this.editorNode = node}/>
    </div>;   
   }

  onChange = (event) => this.editorNode.focus();
}
```

This should cause the editor to focus on any input change (useless really but it should work). However, I cannot access the focus() method from the node due to provide. I have a workaround by just adding the __provided prop to the editor, which bypasses the provide wrapper, but I think there should be a better solution.

**Comment by timbur** [comment]
The `import 'react-redux-provide/lib/install'` method automatically wraps *all* React components.  There should be `wrappedComponent` on the `ProvideEditor` instance that is the `Editor` instance.

**Comment by psachs21** [comment]
I had tried this:
```
ref={node => this.editorNode = node.refs.wrappedInstance}
```

and that works but throws the following:

```
index.js?8a51:37 Uncaught TypeError: Cannot read property 'refs' of null
```

That line refers to `node` being null.

**Comment by psachs21** [comment]
I can guard against the error, but it seems hacky, I'm not sure why node would ever be null.

**Comment by timbur** [comment]
I think maybe it has something to do with the component's lifecycle.  But I'm not entirely sure.  React's docs include an example where they check for `null` as well: https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute.  Searching for the term "null" on that page also sort of explains some things.  And then within the complete example code's comments: "The ref attribute is a callback that saves a reference to the component to this.myTextInput when the component is mounted."

Also, I just noticed I told you the wrong thing (`wrappedComponent`) but you figured it out (`wrappedInstance`).  Sorry about that.

**Comment by psachs21** [comment]
Don't worry about it. No damage done. You're right though, they even guard against null in the examples. Thanks for the help.
