### ISSUE TITLE
Reduce complexity of a documentation

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#29]
So after a while I am finally on a project where I can give this a test drive. However reading through the readme I got somewhat overwhelmed since last time I read it. It seemed so simple back then. Now there is a whole bunch of new stuff and compared to pure Redux, this is way too complex for a new comer. 

I would like to suggest to keep just essentials in readme and move everything else to separate docs.

**Comment by timbur** [comment]
Yeah I realize it seems daunting at first.  Everything is almost exactly the same as what you're used to except for replication, subscriptions, and thunk API.  I'm trying to solidify everything and work out all of the kinks to the point where I can show a real world example, which should help folks understand the purpose of each section of the documentation and why most of it is necessary.  I promise that it is all actually quite simple, but I agree that it is overwhelming without being able to link each concept to something real world.  The preliminary examples/tutorials should hopefully be ready by the end of this week.  I'm planning on including flow charts and all that.  And at some point I will be doing the more traditional style of documentation using `gh-pages` and will try to make the README more concise.  Does that sound good?

**Comment by FredyC** [comment]
Thanks, that definitely sounds like a good way to go. Looking forward to it.
