### ISSUE TITLE
Unit testing providers

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#32]
Main idea for some basic tests is probably to dispatch action and assert that resulting state has correct form. My first question is how to actually get hands on store for a single provider?

From what I understand, these stores are created basically when some component is wrapped into `provide` function. Do I really need whole component or can I fool it somehow?

Looking at [provide-array tests](https://github.com/loggur/provide-array/blob/master/test/index.spec.js) the impression is that's really a way, but frankly I don't like that at all. I would really like to have some readable tests focused around checking those functions instead of that *garbage* that's hard to reason about. At this point I have a feeling that pure redux kinda wins here unless you have some ace up in your sleeves :)

**Comment by FredyC** [comment]
Consider following simple provider...
```js
export const actions = {
	testAction(key) {
		return { type: 'TEST', payload: { key }};
	},
};

export const reducers = {
	main(state = '', action) {
		if (action.type === 'TEST') {
			return action.payload.key;
		}
		return state;
	},
};
```

I tried something along these lines in my tests, but that's probably far from real solution. I did not even tried to execute this as those `props` there obviously nonsense as I don't have them defined anywhere...

```js
	const providerInstance = instantiateProvider({ props: { testAction, main }}, provider);
	const store = createProviderStore(providerInstance);
```

**Comment by FredyC** [comment]
Ok, so I've been reading up how to actually [write unit tests for redux](http://redux.js.org/docs/recipes/WritingTests.html#async-action-creators) and found out about module [redux-mock-store](https://github.com/arnaudbenard/redux-mock-store). That might be actually reused here too. Only part that is missing is to create middleware which would process provider's reducers correctly to setup the state. I am not entirely sure how to do that easily.

**Comment by FredyC** [comment]
I think I am almost there, but I am missing something apparently.
```js
import test from 'ava';
import { actions, reducers } from 'providers/main';

import { combineReducers } from 'redux';
const combinedReducer = combineReducers(reducers);

const middleware = ({ dispatch, getState }) => (next) => (action) => {
	return combinedReducer(getState(), next(action));
};

import configureMockStore from 'redux-mock-store';
const mockStore = configureMockStore([middleware]);

test.beforeEach((t) => {
	t.context.store = mockStore({});
});

test('test provider', (t) => {
	const action = actions.testAction('foo');
	t.context.store.dispatch(action);
	t.deepEqual(t.context.store.getState(), { main: 'foo' });
});
```

The `combinedReducer` itself works correctly, it is returning `{ main: 'foo' }`. It goes through middleware as well, but getting state in that test yields `{}`. Must be something small and silly I am missing here...

**Comment by timbur** [comment]
Yeah the unit tests on the current provider packages definitely aren't meant as an example.  😄   Those are left over from the very beginning when I was figuring everything out.  I'll replace them with much better tests at some point.

You were on the right track with your 2nd comment.  All you need is the `instantiateProvider` function.  It creates the store on the provider instance so that it's accessible via `providerInstance.store`.  The `createProviderStore` is used internally by `instantiateProvider`.

If you can show me an example of something you're trying to test, I'll show you what I think is the best way to test it.  👍

**Comment by FredyC** [comment]
Doesn't seem it would be that easy...

```js
import { actions, reducers } from 'providers/main';

import { instantiateProvider } from 'react-redux-provide';
const providerInstance = instantiateProvider({ props: {} }, { actions, reducers });
```

```
D:\workspace\ents\aroundworld\node_modules\react-redux-provide\lib\instantiateProvider.js:486
    } else if (typeof context[key] !== 'undefined') {
                             ^

TypeError: Cannot read property 'providers' of undefined
    at getFromContextOrProps (D:\workspace\ents\aroundworld\node_modules\react-redux-provide\lib\instantiateProvider.js:486:30)
```

As I said I want to test providers in that way, when I dispatch an action, the state will be modified accordingly. Nothing more at this point.

**Comment by timbur** [comment]
I'll add that most unit tests probably won't need the provider to be instantiated (and the store shouldn't need to be mocked).  Since all of the `actions`, `reducers`, `merge`, `key`, `onInstantiated`, `onReady`, etc. should all be pure functions, it should just be a matter of testing each function individually.  The only things that might need instantiation are `middleware` and `enhancer` (but I think you could actually test those by themselves too).

That said, it is probably more intuitive to just create the store, dispatch an action, and check the states afterwards.  So here's how you'd do that:

```js
import fooProvider from 'providers/fooProvider';  // no need to destructure; just export a single object
import { instantiateProvider } from 'react-redux-provide';

const providerInstance = instantiateProvider({ props: {} }, fooProvider);

describe('fooProvider', () => {
  it('should set foo', () => {
    providerInstance.store.dispatch(provider.actions.setFoo('bar'));

    expect(providerInstance.store.getState()).toBe('bar');
  });
});
```

If this isn't what you're looking for, can you show me a full example?

**Comment by FredyC** [comment]
If you look above, that's essentially what I tried and it's crashing with that error. And I need to destructure because I don't export default, but I export actions and reducers individually.

**Comment by timbur** [comment]
Ohh sorry, just include a `context` object.  The `instantiateProvider` function expects something resembling a React component instance, which always has `this.context` on it.  I suppose I could check for `context` but that should honestly *never* happen in a real setting.  Just include an empty `context` object when instantiating the provider:

```js
import fooProvider from 'providers/fooProvider';  // no need to destructure; just export a single object
import { instantiateProvider } from 'react-redux-provide';

const providerInstance = instantiateProvider({ props: {}, context: {} }, fooProvider);

describe('fooProvider', () => {
  it('should set foo', () => {
    providerInstance.store.dispatch(provider.actions.setFoo('bar'));

    expect(providerInstance.store.getState().foo).toBe('bar');
  });
});
```

**Comment by FredyC** [comment]
Hah, indeed it worked! Perhaps `instantiateProvider` could handle those missing objects there more gracefully so I don't need to actually specify those, but otherwise it looks just fine.

I will dive into writing real unit tests now and see if I run into some issues. Thanks for you help, I was already about to give up and return to pure redux :)

**Comment by timbur** [comment]
My apologies!  I know these things can be really frustrating.  I wish there was more time in a day so I could work on it more while also having better documentation, which would include the best ways to test everything.

I'll say one more thing about `context`.  When you include a `context` object, you can also test multiple providers where one might use the other, like this:

```js
import { someProvider, anotherProvider } from 'providers';
import { instantiateProvider } from 'react-redux-provide';

// you can make all `anotherProvider` instances auto-subscribe to all `someProvider` instances
anotherProvider.subscribeTo = {
  someProvider(someProviderInstance, anotherProviderInstance) {
    const someState = someProviderInstance.store.getState();
    const someAction = anotherProviderInstance.actions.doSomething(someState);

    anotherProviderInstance.store.dispatch(someAction);
  }
};

const context = {};
const someProviderInstance = instantiateProvider({ props: { something: 'cool' }, context }, someProviderInstance);
const anotherProviderInstance = instantiateProvider({ props: { somethingElse: 'awesome' }, context }, anotherProvider);

describe('anotherProvider', () => {
  it('should know when someProvider does something', () => {
    someProviderInstance.store.dispatch(someProviderInstance.actions.setSomething('sweet'));

    expect(anotherProviderInstance.store.getState().someProviderInstanceDidSomething).toBe('sweet');
  });
});
```

The `context` object also allows you to get other provider instances, create other provider instances, and/or find other provider instances.  See the [Thunk API](https://github.com/loggur/react-redux-provide#thunk-api) section of the README.  Also see [`provide-user`'s `createUser` function](https://github.com/loggur/provide-user/blob/f618c394849795fe74cc3ad7e2700e928d3259c3/src/index.js) where it uses the [thunk API](https://github.com/loggur/provide-user/blob/f618c394849795fe74cc3ad7e2700e928d3259c3/src/index.js#L24) to [find another user instance](https://github.com/loggur/provide-user/blob/f618c394849795fe74cc3ad7e2700e928d3259c3/src/index.js#L53) matching the attempted `userName` to prevent duplicates, and then if the `userName` does not yet exist, it [creates the user instance](https://github.com/loggur/provide-user/blob/f618c394849795fe74cc3ad7e2700e928d3259c3/src/index.js#L28) and [finally dispatches the `CREATE_USER` action which sets the user's state (password hash, etc.)](https://github.com/loggur/provide-user/blob/f618c394849795fe74cc3ad7e2700e928d3259c3/src/index.js#L29).

**Comment by timbur** [comment]
How's it going?  You have me worried now that you might give up on trying this library lol.  😁

**Comment by FredyC** [comment]
Sorry, I was kinda away. I will something today, but mostly tomorrow. I'll let you know if I run into something. Not giving up right now because I still want to use elegance of `provide` function :)

**Comment by timbur** [comment]
I update the [`provider-boilerplate`](https://github.com/loggur/provider-boilerplate) tests and removed the devDependency on React since it was never actually needed (https://github.com/loggur/provider-boilerplate/commit/d4a7dde05008de2dd07b721209e3649625f2581d).  Thanks for pushing this in the right direction @FredyC!

**Comment by FredyC** [comment]
Looking good, thanks. Still would it be possible to handle more gracefully when `props` and `context` are missing there? It feels rather awkward when this needs to be specified in tests. I also ran into other unhandled exceptions there like when no reducers are present on provider.

**Comment by timbur** [comment]
Hmm, alright.  I'll add some checks for all of that.  👍

**Comment by timbur** [comment]
Okay, added some defaults in ccff8e4549e0f8f212fbc13539d2fbe45b8228a1.  I'm curious though.  When would you ever have actions but no reducers (or vice versa)?

**Comment by timbur** [comment]
Forgot to mention, there's actually a shortcut for dispatching actions.

Instead of this:
```js
providerInstance.store.dispatch(providerInstance.actions.doSomething('fun'));
```

You can just do this:
```js
providerInstance.actionCreators.doSomething('fun');
```

I've added this bit of info to the Protips section of the README and updated the tests to reflect this.

**Comment by FredyC** [comment]
Ok that's a bit letter, but why did you actually handled `context` only but `props` are still necessary? Is there some reason for it? It looks to me exactly same issue for unit testing. You need to specify that empty object there without any reason while it can be simply specified in code itself and nothing should be broken by it?

I don't have a case without reducers, it was just coincidence that I was checking those unit tests and I had not reducers yet, so it has throw that error.

Regarding `providerInstance.actionsCreators` I cannot use that unfortunately because I need to keep context of action function to be the provider object (not your instance, but mine). I have some dependency injection so I can mock network request more easily, so I am dependant on `this`.

**Comment by timbur** [comment]
Ah, yeah, at the top of my todo list today is actually:
```
allow instantiateProvider(provider)
```

😁 

Meant to do it last night but it got late!  I'll do it real quick...

**Comment by timbur** [comment]
Okay I think 963dbf768c8522ee2950f0dbfe5a6c4db5a9c09b should allow that now, hopefully.  I'll do more testing later after I've have my morning coffee lol.  👍

**Comment by FredyC** [comment]
Now with providers using replication I have a problem unit testing again. I've created provider like this. It's really just about initializing store asynchronously and state is not going to change ever.
```js
import { actionValidator } from 'validator';
import { createSchema } from 'redux-action-schema';

const schema = createSchema([
	['locatingUser'],
	['userLocated', actionValidator.userLocation],
	['userNotLocated'],
]);

const types = schema.actions;

const actions = schema.actionCreators;

const reducers = {
	location: (state = null) => state,
};

function UserLocationProvider({ request }) {
	async function getInitialState(_, setState, store) {
		try {
			const location = await request.findUserLocation();
			actionValidator.userLocation(location);
			setState(location);
			store.dispatch(actions.userLocated(location));
		} catch (err) {
			store.dispatch(actions.userNotLocated(err));
		}
	}

	return {
		types, actions, reducers,
		replication: {
			replicator: { getInitialState },
		},
	};
}

export default UserLocationProvider;
```
I tried unit test like this, the `onReady` is invoked, but `getInitialState` in a provider isn't.
```js
import UserLocationProvider from 'providers/userLocation';

test('is initialized with user location from remote service', (t) => {
	t.plan(2);

	const expected = { name: 'MyCity' };
	const request = Request.methods({
		findUserLocation() {
			t.pass('request called');
			return setImmediate(() => Promise.resolve(expected));
		},
	});

	const provider = UserLocationProvider({ request });
	provider.replication.replicator.onReady = (key, store) => {
		const { location } = store.getState();
		t.deepEqual(location, expected);
	};
	instantiateProvider({ props: {}, context: {}}, provider);
});
```

**Comment by timbur** [comment]
I'm short on time today/this weekend, so I'll have to keep it brief.

I think the problem is that you're missing a `key` on your provider and/or replication.  Sorry that the docs aren't clear on this (they say a `null` key disables replication when it's actually any falsy value - i.e., undefined).  I'll update them now.  You may also want to get into the habit of including `reducerKeys` with your `replication` (to avoid any confusion in the future), setting it to either `true` or `['location']`.  It isn't `true` by default because in most cases, you'll only be replicating a handful of states, while others are used internally by your provider.

Also, it doesn't matter too much, but for future reference you can use this shortcut (instead of `provider.replication.replicator.onReady`):
```js
    provider.onReady = (providerInstance) => {
        const { location } = providerInstance.store.getState();
        t.deepEqual(location, expected);
    };
```

And remember that you can now use `instantiateProvider(provider)` instead of `instantiateProvider({ props: {}, context: {} }, provider)`.

Let me know if setting the `provider.key` solves your problem.  If not, I'll take a closer look when I get a chance.

**Comment by FredyC** [comment]
Ok just want to let you know that adding `key` in a test file has fixed issue. Might be useful to actually throw some exception if you unable to find valid key. Within a different test I've run into error `Cannot read property 'toString' of undefined` which referred [to this line of code](https://github.com/loggur/react-redux-provide/blob/master/src/instantiateProvider.js#L103). Might be good to handle that as well.

Anyway I got another question. Instead of `getInitialState` I've actually used `onInstantiated` to dispatch initial action to load state. However the `onReady` doesn't work for this since action is asynchronous. I guess that only way how to unit test that would be actually listening for action on store or do you have any other idea?

**Comment by timbur** [comment]
`onInstantiated` occurs immediately as the provider is instantiated, while `onReady` is dependent on the provider's replication and is only called once all states have been initialized by the replicator.  If you're going to use `onInstantiated` + custom store initialization instead of replication, then you will need to test things similar to however you would with vanilla Redux.

**Comment by timbur** [comment]
Feel free to reopen!
