### ISSUE TITLE
Can getInstance accept array?

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#40]
I have a `locale` provider with reducer `locale` which I want to use in other provider.
```js
const doCitySearch = (searchCity) => (dispatch, getState, { getInstance }) => {
    getInstance({ locale: true }) // ???
    getInstance(['locale']) // easier to understand
    const { locale } = getProviderState(['locale']);
}
```
First case is obviously weird for such simple cases. I mean how does it make sense to supply _state_ with some values which you obviously don't have.

Second one is bit more understandable, but last one would be best. It would be a wrapper around `getInstance` and create a state with requested values. 

Also it feels rather awkward that I have to specify getState in arguments while I don't need it. I understand that `getState` comes from `redux-thunk`, but still...

**Comment by timbur** [comment]
I guess it might make sense to allow passing a string to `getInstance` while also adding a `getInstances` method as well, which would accept an array.

Any particular reason why `locale` and `citySearch` are separate providers?  Based on the limited information I have here, it looks like `citySearch` is dependent on `locale`, so they might as well be on in the same:
```js
const doCitySearch = (searchCity) => (dispatch, getState) => {
    const { locale } = getState();
    // etc.
}
```

I'm just curious about the reason behind keeping them separate.  😁

**Comment by FredyC** [comment]
Those are separate because `locale` will be used in other providers as well. There will be more of various API calls that needs it.

Not sure if you understood me correctly with that `getInstance`. It's that doesn't make any sense to create some virtual state with `true` values, so I though essentially about passing only state keys. It shouldn't be name of provider itself.

**Comment by timbur** [comment]
The `getInstance` method uses the same algorithm that components use when providers are assigned to them, which makes a lot of sense in the case of a dynamic provider (with a `key` function).  If you had a `key` function that returns some long-ish string, you don't want to be typing that string out every time, you'd rather just automatically use the `key` function right?...  especially if there's a chance you might change the `key` function in the future (prevents having to update your code more than once).  For example, it's originally intended to be used for things like `getInstance({ userId })`.  But your suggestion seems warranted for static providers where you know the `key` will always be the same, so I will probably add the ability to `getInstance('locale')`.

**Comment by timbur** [comment]
The above commit should do what you want.  Let me know if there are any issues.

**Comment by FredyC** [comment]
Thanks, will try it later.
