### ISSUE TITLE
Dynamic key and replication

### ISSUE THREAD

**Issue by FredyC** [loggur/react-redux-provide#41]
Hey. This is some other idea what I think would be nice to include. I am fairly certain that you have mentioned something like this before, but I am failing to find it. After looking bit more closely to `localforage` replicator, I've got bit more of understanding what are replicators useful for.

I am now thinking about scenario that I have search results from 3rd party service based on some user input. I have a provider with dynamic key based on that input. Then I would like to use `getInitialState` to actually retrieve search results so essentially cache for repeated input will be created. Together with `localforage` replicator those results would be nicely stored in user browser and reused later.

However I am failing on that part as I am unable to get that user input there. Only way I see is to read it from the `key`. Is it true that `key` has to be unique throughout all providers? In that case I have to prefix that value with something and then in `getInitialState` parse it again? That feels totally weird.

What about actually adding something similar to `key`, but accepting even a object as result that can be made of props? That value could be then passed to `getInitialState` along with key and reducerKey. It would fairly increase ease of use.

**Comment by timbur** [comment]
Hey @FredyC I hope everything is going well.  Sorry I never replied to this!  I've been super busy moving, working, etc.  I should finally have some extra time over the next week and I'll take a closer look at this thread and the others and see if I can finalize an API that will cover (almost) everything.  You've made a ton of really good observations and suggestions.  And after that I'll *finally* try to put together proper documentation.

**Comment by FredyC** [comment]
Hey. Yes everything is fine. I had no need to dive deeper into providers lately as it works so far for all the needs I have. There is another project upcoming in near future that will be more CRUD-like with routing and everything, so I am sure that's gonna be next level of providers for me :)

**Comment by FredyC** [comment]
Same reason to close as in #39
