### ISSUE TITLE
react v16, prop-types support

### ISSUE THREAD

**Issue by sh-spartan** [loggur/react-redux-provide#44]
Hi, love your library, thank you for sharing it! :)

Are there any plans to update this to depend on `react` v16.x, and the now broken out `prop-types`? 

If I try to use webpack and make my app depend on v16 only, `react-redux-provide` will break since PropTypes is no longer available on the react lib. https://github.com/loggur/react-redux-provide/blob/master/src/provide.js#L1

**Comment by timbur** [comment]
<3

Yes I will update everything for react v16 soon.

In the mean time, I wonder if you might be able to do something like this:
```
// setPropTypes.js

import React from 'react';
import PropTypes from 'prop-types';

React.PropTypes = PropTypes;
```

And then `import './setPropTypes';` before anything else within your app.

I'm not entirely sure if that would work though as a temporary fix.  Depends on whether or not webpack or whatever agrees.

**Comment by sh-spartan** [comment]
Didn't work for my particular setup, but I don't mind waiting a bit for this lib to sync up with react.

Thanks again, great work :)

**Comment by timbur** [comment]
@sh-spartan v7.0.0 should now work with react v16!  😃
