### ISSUE TITLE
componentDidMount called out of order

### ISSUE THREAD

**Issue by sh-spartan** [loggur/react-redux-provide#45]
I have a component set to make a remote call for data in `componentDidMount`. The server is mocked so I get the response back synchronously, store gets updated fine. However the component isn't re-rendering due to the store change. Re-doing the api call and the component re-renders.

I dug into the library and found that this is due to the following order of operations for the initial render:
1. `componentDidMount` called on my component
2. store is updated
3. `update` is called in the provide lib, but `this.unmounted` is true, so it doesn't update
4. `componentDidMount` called on `Provide.prototype`, setting `this.unmounted` to false

As step 4 sets `unmounted` to `false`, then re-doing the api call succeeds since `update` does its thing successfully.

Shouldn't step 4 happen first, then step 1? Or I'm doing something wrong?

**Comment by sh-spartan** [comment]
Wrapping my line like so and the initial render is fine. But shouldn't this work for synchronous operations too?

`window.setTimeout(() => this.props.getStuff(), 0)`

**Comment by timbur** [comment]
May I see your code?  I'm not sure I follow.

**Comment by sh-spartan** [comment]
```js
// stuffs.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

export default class Stuffs extends Component {
  static propTypes = {
    getStuff: PropTypes.func.isRequired,
    stuff: PropTypes.any.isRequired,
  }

  componentDidMount () {
    this.props.getStuff()
  }

  render () {
    return (
      <div>
        {/* code to render the stuff if present */}
      </div>
    )
  }
}

// stuffs-provider.js
import middleware from 'lib/redux-api-middleware'
import Server from 'lib/server'

const GET = 'GET'

const actions = {
  getStuffs: () => ({ type: GET, promise: Server.get('stuffs') }),
}

const initialState = 'fetching'

const reducers = {
  stuffs: (state = initialState, action) => {
    switch (action.type) {
    case 'GET_SUCCESS':
    case 'GET_FAILURE':
      return action.data
    default:
      return state
    }
  }
}

export default { actions, reducers, middleware }
```
With breakpoints set up I see that `componentDidMount` gets called, the store is updated, then `update` in the provide library file does not call `forceUpdate` because `is_unmounted` is true, then lastly `Provide.protoype.componentDidMount` gets called, which switches `is_unmounted` to false.

End result the provider's store has updated, but react-redux-provide ignored the state change and so my component has no data to render still because it has stale props.

If I make that componentDidMount code asynchronous by eg wrapping it in a setTimeout, the store update doesn't occur until after provide does it's thing and so my component re-renders.

**Comment by timbur** [comment]
Where is `<Stuffs />` rendered?

Also, I'm not sure how `redux-api-middleware` works, but at first glance, it looks like the `getStuffs` action isn't going to update the store upon the server's response.  Should it not look something like this?
```js
const actions = {
  getStuffs: () => (dispatch, getState) => dispatch({
    type: GET,
    promise: Server.get('stuffs')
      .then(data => dispatch({ type: 'GET_SUCCESS', data }))
      .catch(data => dispatch({ type: 'GET_FAILURE', data }))
  })
}
```

**Comment by sh-spartan** [comment]
I'm afraid I don't have time to figure out why I was experiencing the behavior I was, at least for a while. I'll close this issue and may be able to revisit the problem later, in which case I'll re-open this with my findings.

The middleware was just a bit of simple logic to process promises coming out of `Server` and create various redux actions accordingly. In this case, a `GET` followed by a `` `${GET}_SUCCESS` ``.
