### ISSUE TITLE
Efficient rendering

### ISSUE THREAD

**Issue by timbur** [loggur/react-redux-provide#5]
With c958d8d47adaa10f25634944eb039960bb23b859, we removed the filtering of `propTypes` which will cause unnecessary re-rendering when `props` are updated that not all components care about.

- [ ] Fix `shouldComponentUpdate` to only compare the `props` we care about.
- [ ] Create tests to verify efficient rendering.

**Comment by timbur** [comment]
Let's revisit this later on when a better solution than filtering the `propTypes` becomes apparent.  Perhaps some kind of memoization and/or flag?

**Comment by namjul** [comment]
I read your article and find your approach a great alternative.
At the moment i am using immutable.js,  reselect and pureRenderMixin to make sure my components only rerender when their props change. Can you explain how this is achieved with react-redux-provide? I guess reselect would still make sense in the provide.merge function. And pureRenderMixin i am not sure. thx

**Comment by timbur** [comment]
It's designed with the assumption that your components are pure, so it works the same as `pureRenderMixin` (ultimately uses a shallow comparison of your props to see if any have changed) but should actually already be slightly more efficient, overall.  There are a couple of things that can be done to make it even more efficient, which is what I opened this issue for.  :)

**Comment by namjul** [comment]
thx, have to play with it a bit :)
