### ISSUE TITLE
redux-provide vs redux-saga

### ISSUE THREAD

**Issue by ms88privat** [loggur/react-redux-provide#9]
@timbur The concept of redux-provide looks really good to me at first sight. 

I have opened this issue to give other users and me more perspective about your project. I recently looked into a lot of new concepts, including [redux-saga](https://github.com/yelouafi/redux-saga). Right now, I'm a bit lost.

Redux-saga is helping a lot in managing complex control flows (multi-step async operations). So it is not in competition with your project but I'm also not sure how they are playing together nicely. Maybe you are aware of redux-saga and you could help me out here.

In any case, I will give it a try and let you know.

Thank you very much

**Comment by timbur** [comment]
Use redux-thunk and return a function for async actions. I believe redux-saga uses async await though which I think returns a promise, so when I get back to a keyboard, I'll look into supporting promises in provide-page's automatic server rendering.

**Comment by ganarajpr** [comment]
Actually redux-saga uses generators for handling the control flow. I really like the ideas behind react-redux-provide and like the OP mentioned, I believe react-redux-provide has no opinion towards how to manage side effects. 

I am not really sure as well, as to how we could potentially use both these things together. From my inital perfunctory look I am guessing one could provide redux-saga as an enhancer to `provide` using `unshiftEnhancer` or `pushEnhancer`. 

But yeah, I am also interested in knowing how they can work well together ( if at all. )

**Comment by timbur** [comment]
I've checked out `redux-saga` and I believe you should be able to use the two together quite easily.  :)

Looking at https://github.com/yelouafi/redux-saga/tree/master/examples/cancellable-counter/src, I think it can become a provider like so:
```js
import createSagaMiddleware from 'redux-saga'
import { take, put, call, fork, race } from 'redux-saga/effects'
import { CANCEL } from 'redux-saga/utils'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD'
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC'
export const CANCEL_INCREMENT_ASYNC = 'CANCEL_INCREMENT_ASYNC'
export const SHOW_CONGRATULATION = 'SHOW_CONGRATULATION'
export const HIDE_CONGRATULATION = 'HIDE_CONGRATULATION'

const action = type => ({type})

function delay(millis) {
    let tid
    const promise = new Promise(resolve => {
      tid = setTimeout( () => {
        resolve(true)
      }, millis )
    })

    promise[CANCEL] = () => clearTimeout(tid)
    return promise
}

const actions = {
  * incrementAsync() {
    yield call(delay, 1000)
    yield put(action(INCREMENT))
  },

  * watchIncrementAsync() {
    while(yield take(INCREMENT_ASYNC)) {
      // starts a 'Race' between an async increment and a user cancel action
      // if user cancel action wins, the incrementAsync will be cancelled automatically
      yield race([
        call(actions.incrementAsync),
        take(CANCEL_INCREMENT_ASYNC)
      ])
    }
  },

  * onBoarding() {
    let nbIncrements = 0
    while(nbIncrements < 3) {
      const winner = yield race({
        increment : take(INCREMENT),
        timeout   : call(delay, 5000)
      })

      if(winner.increment)
        nbIncrements++
      else
        nbIncrements = 0
    }

    yield put(action(SHOW_CONGRATULATION))
  },

  * rootSaga() {
    yield fork(actions.watchIncrementAsync)
    yield fork(actions.onBoarding)
  }
}

const reducers = {
  incrementAsyncPending(state = false, action) {
    switch (action.type) {
      case INCREMENT_ASYNC:
        return true
      case INCREMENT:
      case CANCEL_INCREMENT_ASYNC:
        return false
      default:
        return state
    }
  },

  counter(state = 0, action) {
    switch (action.type) {
      case INCREMENT:
        return state + 1
      case DECREMENT:
        return state - 1
      case INCREMENT_IF_ODD:
        return state % 2 ? state + 1 : state
      default:
        return state
    }
  },

  congratulate(state = false, action) {
    switch (action.type) {
      case SHOW_CONGRATULATION:
        return true
      case HIDE_CONGRATULATION:
        return false
      default:
        return state
    }
  }
}

const middleware = createSagaMiddleware(actions.rootSaga)

export default { actions, reducers, middleware }

// There's a chance you might also have to do this:
// const mapDispatch = () => {}
// export default { actions, reducers, middleware, mapDispatch }
// Or mapDispatch may have to be something specific to `redux-saga`.
```

You'd also need to add some extra `actions` for the `onClick` events within the [`Counter` component](https://github.com/yelouafi/redux-saga/blob/master/examples/cancellable-counter/src/components/Counter.js) so that it is properly decoupled from the `provider`.

I haven't tested this but I'm certain it's possible for `redux-saga` to work within providers and could potentially add some nice flow to them.  I'll play around with this some more when I get a chance so that you all can have a working example.

**Comment by ynohtna** [comment]
@timbur I am happy to confirm that expressing Sagas as providers in the manner shown works really well. Thanks!

**Comment by timbur** [comment]
Awesome! Good to know!

**Comment by timbur** [comment]
FYI, I just checked out another library, [`redux-loop`](https://github.com/raisemarketplace/redux-loop), and after skimming over it, I think it could possibly be a cleaner/simpler alternative to `redux-saga` and might work better with providers.  Figured I'd mention it here as it could be worth checking out.  :)
